### ISSUE TITLE
 lfs.dir() does not work on 32bit Windows builds?

### ISSUE THREAD

**Issue by subsoap** [britzl/defold-lfs#1]

**Comment by britzl** [comment]
Solved in https://github.com/britzl/defold-lfs/commit/a66a751ac99dedccda36198c5f8dcdca9edcb7a4

**Comment by subsoap** [comment]
For whatever reason, this is not working in win32 builds again.

**Comment by subsoap** [comment]
[lfs_test.zip](https://github.com/britzl/defold-lfs/files/3881926/lfs_test.zip)

Simple test project, bundle for win32 debug, does not work to get dir.

**Comment by britzl** [comment]
Do you get an error or any indication of what's wrong?

**Comment by subsoap** [comment]
No error, when building win32 c_file is always empty

**Comment by subsoap** [comment]
Working as expected now with beta bob in slack
